apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-test
  labels:
    k8s-app: k8s-test
spec:
  replicas: 1
  selector:
    name: k8s-test
  template:
    metadata:
      labels:
        name: k8s-test
    spec:
      containers:
      - name: k8s-test
        image: index.caicloud.io/caicloud/k8s-test
        imagePullPolicy: "Always"