apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
  labels:
    k8s-app: lifcycle
spec:
  containers:
  - name: test
    image: busybox
    lifecycle:
      postStart:
        exec:
          command:
            - echo
            - "start!"
      preStop:
        exec:
          command:
            - curl
            - localhost:8765/start
        # httpGet:
        #   path: "/start"
        #   port: 8765
    command:
    - sleep
    - "10"
  - name: executor
    image: busybox
    imagePullPolicy: Always
  restartPolicy: Never