apiVersion: v1
kind: ReplicationController
metadata:
  name: fsnotify
  labels:
    k8s-app: fsnotify
spec:
  replicas: 1
  selector:
    name: fsnotify
  template:
    metadata:
      labels:
        name: fsnotify
    spec:
      containers:
      - name: fsnotify
        image: index.caicloud.io/caicloud/fsnotify
        imagePullPolicy: "Always"
        volumeMounts:
          - name: config-volume
            mountPath: /tmp/
      volumes:
        - name: config-volume
          configMap:
            name: kubeconfig
            items:
            - key: some-file.txt
              path: foo
